### ISSUE TITLE
Missing C bindings when using operator-sdk v0.13.0

### ISSUE THREAD

**Issue by carlosjgp** [xUnholy/operator-sdk-github-action#8]
https://github.com/carlosjgp/vault-secret-operator/commit/e01e7d05f2e6d1b8ac948abfdf43dfffd19e7e57/checks?check_suite_id=365519803
```
    - name: Operator-SDK Action
      uses: xUnholy/operator-sdk-github-action@v1.0.0
      env:
        RELEASE_VERSION: v0.13.0
        CGO_ENABLED: 0
      with:
        image: "carlosjgp/vault-secret-operator-controller"
        tag: v0.1.0
```

```
# github.com/carlosjgp/vault-secret-operator/cmd/manager
loadinternal: cannot find runtime/cgo
/usr/lib/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find Scrt1.o: No such file or directory
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find crti.o: No such file or directory
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lssp_nonshared
collect2: error: ld returned 1 exit status
```

A suggested solution for [similar issue](https://github.com/uber/h3/issues/103#issuecomment-408651010) is to install `musl-dev`
